### ISSUE TITLE
sentence quality

### ISSUE THREAD

**Issue by eubinean** [eubinecto/idiom2collocations#3]
## Why?
We need a way to do:
- sentence -> quality

## How?
> Goal: sentence -> quality

So? how does the function measure the quality?

### TFIDF
Start with a tfidf model. What do I need?
you must first have the tfiddf lookups for each idiom.
it will be better to save them as ndjson, then. That will suit me better than tsv. 

### LDA

**Comment by eubinecto** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/56193069/117564249-2a164000-b0e6-11eb-844e-0f446855f113.png">
